name: flutter_reload
description: "Simplifies error handling by managing low-level errors, allowing developers to focus solely on business logic."
version: 0.0.8
homepage: https://github.com/CakeResume/flutter_reload
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0